version: "3.8"

services:
  redis_binance:
    image: redis:7.2
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass my_master_password
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540" # RedisInsight web UI port
    depends_on:
      - redis_binance
    volumes:
      - redisinsight-data:/db

volumes:
  redis_data:
    driver: local
  redisinsight-data:
