version: "3.8"

services:
  redis_binance:
    image: redis:7.2
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass my_master_password
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
